### ISSUE TITLE
Space Fuel Handling Missing

### ISSUE THREAD

**Issue by Sambo726** [Bayouking1/DU-DamageReport#3]
There is no LUA Parem. to add space fuel tank handling to get correct fuel lvl.

**Comment by Bayouking1** [comment]
should be fixed

**Comment by ristlin** [comment]
The variable shows up in edit lua, but does not appear in the parameter window.

EDIT: Actually, it may be a bug with data banks. Sometimes space fuel tank shows up in user parameters and sometimes it doesn't.

**Comment by GeneralTragedy** [comment]
appears to be because of a changelog comment for the rename fix?
