### ISSUE TITLE
Switching to Time tab causes CPU overload

### ISSUE THREAD

**Issue by ristlin** [Bayouking1/DU-DamageReport#6]
Switching to Time tab causes CPU overload and crashes the LUA script.

**Comment by ricdk** [comment]
I was also going to report this...

**Comment by Bayouking1** [comment]
Will have a look as soon as I get home how many screens are you running when it overloads?

**Comment by ricdk** [comment]
One screen...

**Comment by Bayouking1** [comment]
Clear databank and try again pls

**Comment by ristlin** [comment]
I’ve cleared databank, replaced screen, and done several combinations to clear the error. The error will clear, but if you try and go back to time tab it will crash again.

**Comment by Bayouking1** [comment]
Are you runing any other PB at the same time?

**Comment by ristlin** [comment]
No, just the damage report

**Comment by Bayouking1** [comment]
Try deleting the Databank

**Comment by ristlin** [comment]
Looks fixed now. Thank you!
